// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeostpqcrvviyacpbxdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlb3N0cHFjcnZ2aXlhY3BieGRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzQ1OTUsImV4cCI6MjA3Mjc1MDU5NX0.I3Y4RZtB6qE4g0bNATqvHLpXZRSLLRpzAi1ndbQDSOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});